name: CI

on:
  push:
    branches: [ main, "releases/**" ]
  pull_request:
    branches: [ main, "releases/**" ]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch the parent branch information for SonarCloud
          fetch-depth: 0

      - name: Read Node Version
        run: echo "NODE_VERSION=$(jq -crM .engines.node < package.json)" >> $GITHUB_OUTPUT
        shell: bash
        id: node_version

      - name: Use Node.js ${{ steps.node_version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.node_version.outputs.NODE_VERSION }}'
          cache: 'npm'

      - name: Run Lint
        run: make do-lint

      - name: Run Build
        run: make dist

      - name: Run Tests
        run: make test

      # Run SonarCloud after completing tests and generating code coverage report
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dproject.settings=./.sonar-project.properties
